// Writes docs/assets/price-data.js, the data behind the body-weight price widget in docs/. `npm run docs:data` after changing a price or a table.
import { writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { catalogPricing, SCORING } from '../scoring.js';
import { BW_MAX, BW_MIN, BW_STEP, REPS_TABLES } from '../strengthLevelTables.js';

const BODYWEIGHT_ROWS: [string, string][] = [
  ['pushups', 'Push-up'],
  ['pullups', 'Pull-up'],
  ['chinups', 'Chin-up'],
  ['dips', 'Dips'],
  ['burpees', 'Burpee'],
  ['abrolls', 'Ab-roll'],
  ['abrollsassisted', 'Assisted ab-roll'],
  ['lunges', 'Lunge'],
  ['legraise', 'Leg raise'],
  ['squats', 'Squat'],
  ['situps', 'Sit-up'],
  ['calfraises', 'Calf raise'],
];

export interface DocsData {
  ladder: number[];
  bwMin: number;
  bwMax: number;
  bwStep: number;
  bwRef: number;
  exercises: { key: string; label: string; p: number; table: string }[];
  cardio: { run: number; swim100: number };
  tables: Record<string, { novice: number[]; intermediate: number[] }>;
}

export function buildDocsData(): DocsData {
  const exercises = BODYWEIGHT_ROWS.map(([key, label]) => {
    const spec = catalogPricing(key);
    if (!spec || spec.kind === 'lift' || !spec.table) throw new Error(`${key} has no body-weight table`);
    return { key, label, p: spec.p, table: spec.table };
  });
  const tables: DocsData['tables'] = {};
  for (const { table } of exercises) {
    const rows = REPS_TABLES[table];
    if (!rows) throw new Error(`no reps table for ${table}`);
    tables[table] = { novice: rows.map((r) => r[1]), intermediate: rows.map((r) => r[2]) };
  }
  const run = catalogPricing('run');
  const swim = catalogPricing('swim');
  if (run?.kind !== 'flat' || swim?.kind !== 'flat') throw new Error('run and swim must be flat prices');
  return {
    ladder: [...SCORING.LADDER],
    bwMin: BW_MIN,
    bwMax: BW_MAX,
    bwStep: BW_STEP,
    bwRef: SCORING.BODY_LB,
    exercises,
    cardio: { run: run.p, swim100: swim.p * 100 },
    tables,
  };
}

export const DATA_FILE = fileURLToPath(new URL('../../docs/assets/price-data.js', import.meta.url));

export function renderDocsData(data: DocsData): string {
  return `// Generated by src/scripts/build-docs-data.ts (npm run docs:data). Do not edit by hand.\nexport default ${JSON.stringify(data, null, 2)};\n`;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  writeFileSync(DATA_FILE, renderDocsData(buildDocsData()));
  console.log(`wrote ${DATA_FILE}`);
}
